name: nndl_saliency
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  
  # Core
  - pytorch
  - torchvision
  - pytorch-cuda=11.8
  
  # Data processing & Vision
  - numpy
  - pandas
  - pillow
  - opencv
  
  # Metrics & Math (useful for KL, CC, NSS, AUC)
  - scipy
  - scikit-learn
  
  # Visualization & Notebooks
  - matplotlib
  - jupyter
  - ipykernel
  
  # Utilities
  - tqdm
  - gdown