name: nndl_saliency
channels:
  - conda-forge
dependencies:
  - python=3.10
  # Data processing & Vision
  - numpy
  - pandas
  - pillow
  - opencv
  
  # Metrics & Math (useful for KL, CC, NSS, AUC)
  - scipy
  - scikit-learn
  
  # Visualization & Notebooks
  - matplotlib
  - jupyter
  - ipykernel
  
  # Utilities
  - tqdm
  - pip
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu128
    - torch
    - torchvision
    - gdown